# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-22 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': '图片'},
        ),
        migrations.RemoveField(
            model_name='album',
            name='slug',
        ),
    ]
