# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-29 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180922_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': '图片', 'verbose_name_plural': '图片'},
        ),
    ]
