# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-02 17:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('pub_date', models.DateField(null=True, verbose_name='发布日期')),
                ('read', models.IntegerField(default=0, verbose_name='阅读量')),
                ('comment', models.IntegerField(default=0, verbose_name='评论量')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '文章内容',
                'verbose_name_plural': '文章内容',
                'db_table': 'tb_blog',
            },
        ),
    ]
