# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-22 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_myblog_digest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='digest',
            field=models.TextField(verbose_name='文章摘要'),
        ),
    ]
